SUPABASE_URL = "https://ombvqjlhadlvhgkcuskn.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tYnZxamxoYWRsdmhna2N1c2tuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5Nzg1MDIsImV4cCI6MjA3NTU1NDUwMn0.slmPmpKNmk1Z5Okl-_CKW1pSgjYeaBmz2y5tkinjgCo"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tYnZxamxoYWRsdmhna2N1c2tuIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTk3ODUwMiwiZXhwIjoyMDc1NTU0NTAyfQ.JLeAz8cdCn8VCZKXR3HNCgBSkXbrrHimBfIwP9zWsUY"

# MySQL Configuration
MYSQL_HOST = "localhost"
MYSQL_DATABASE = "dexa"
MYSQL_USER = "root"
MYSQL_PASSWORD = "shiva1506"
MYSQL_PORT = 3306
