SUPABASE_URL =" your supabase_url"
SUPABASE_KEY = "your supabase_key"
SUPABASE_SERVICE_ROLE_KEY = "your supabase_service_role_key"

# MySQL Configuration
MYSQL_HOST = "localhost"
MYSQL_DATABASE = "your database name"
MYSQL_USER = "your mysql username"
MYSQL_PASSWORD = "your password"
MYSQL_PORT = 3306


